In [1]:
import pandas as pd
import numpy as np
import os
from pathlib import Path

from sklearn.preprocessing import LabelEncoder
from sklearn.cluster import KMeans
from sklearn.metrics import adjusted_rand_score, silhouette_score
from sklearn.metrics.pairwise import cosine_distances
from sklearn.metrics import pairwise_distances

# Change Working Dir To the Project Working Dir (for Noam)

In [ ]:
# # change the dir to the grandparent directory of the current working directory

# current_dir = Path(os.getcwd())
# grandparent_dir = current_dir.parent.parent
# os.chdir(grandparent_dir)

In [4]:
os.getcwd()  # Check the cwd has updated

'c:\\Users\\noams\\Python Projects\\Audio_processing_project'

In [8]:
raw_data = pd.read_csv(Path("tcav_per_sample_with_acc.csv"))

In [9]:
raw_data.head(13)

,path,concept_name,layer_name,positive_percentage,magnitude,cav_acc,true_label,predicted_label,predicted_probability
0,RAVDESS\original_data\Actor_23\03-01-02-02-02-...,long_constant_thick,module3.blocks.0.conv2,0.0,-0.479544,0.956522,calm,calm,0.999167
1,RAVDESS\original_data\Actor_23\03-01-02-02-02-...,long_dropping_flat_thick,module3.blocks.0.conv2,0.0,-2.054141,0.869565,calm,calm,0.999167
2,RAVDESS\original_data\Actor_23\03-01-02-02-02-...,long_dropping_steep_thick,module3.blocks.0.conv2,0.0,-0.572685,0.782609,calm,calm,0.999167
3,RAVDESS\original_data\Actor_23\03-01-02-02-02-...,long_dropping_steep_thin,module3.blocks.0.conv2,0.0,-1.140559,0.913043,calm,calm,0.999167
4,RAVDESS\original_data\Actor_23\03-01-02-02-02-...,long_rising_flat_thick,module3.blocks.0.conv2,0.0,-0.252294,0.695652,calm,calm,0.999167
5,RAVDESS\original_data\Actor_23\03-01-02-02-02-...,long_rising_steep_thick,module3.blocks.0.conv2,0.0,-1.292134,0.869565,calm,calm,0.999167
6,RAVDESS\original_data\Actor_23\03-01-02-02-02-...,long_rising_steep_thin,module3.blocks.0.conv2,0.0,-0.815764,0.826087,calm,calm,0.999167
7,RAVDESS\original_data\Actor_23\03-01-02-02-02-...,short_constant_thick,module3.blocks.0.conv2,0.0,-0.217394,0.826087,calm,calm,0.999167
8,RAVDESS\original_data\Actor_23\03-01-02-02-02-...,short_dropping_steep_thick,module3.blocks.0.conv2,0.0,-0.479893,0.739130,calm,calm,0.999167
9,RAVDESS\original_data\Actor_23\03-01-02-02-02-...,short_dropping_steep_thin,module3.blocks.0.conv2,0.0,-0.958675,0.826087,calm,calm,0.999167
10,RAVDESS\original_data\Actor_23\03-01-02-02-02-...,short_rising_steep_thick,module3.blocks.0.conv2,0.0,-0.814124,0.956522,calm,calm,0.999167
11,RAVDESS\original_data\Actor_23\03-01-02-02-02-...,short_rising_steep_thin,module3.blocks.0.conv2,1.0,0.311537,0.826087,calm,calm,0.999167
12,RAVDESS\original_data\Actor_02\03-01-07-01-02-...,long_constant_thick,module3.blocks.0.conv2,1.0,0.963829,0.956522,disgust,disgust,0.998985

In [10]:
emotion_encoder, concept_encoder = LabelEncoder(), LabelEncoder()

In [11]:
data_matching_predictions = raw_data.where(raw_data["true_label"] == raw_data["predicted_label"])

In [12]:
data_matching_predictions.head()

,path,concept_name,layer_name,positive_percentage,magnitude,cav_acc,true_label,predicted_label,predicted_probability
0,RAVDESS\original_data\Actor_23\03-01-02-02-02-...,long_constant_thick,module3.blocks.0.conv2,0.0,-0.479544,0.956522,calm,calm,0.999167
1,RAVDESS\original_data\Actor_23\03-01-02-02-02-...,long_dropping_flat_thick,module3.blocks.0.conv2,0.0,-2.054141,0.869565,calm,calm,0.999167
2,RAVDESS\original_data\Actor_23\03-01-02-02-02-...,long_dropping_steep_thick,module3.blocks.0.conv2,0.0,-0.572685,0.782609,calm,calm,0.999167
3,RAVDESS\original_data\Actor_23\03-01-02-02-02-...,long_dropping_steep_thin,module3.blocks.0.conv2,0.0,-1.140559,0.913043,calm,calm,0.999167
4,RAVDESS\original_data\Actor_23\03-01-02-02-02-...,long_rising_flat_thick,module3.blocks.0.conv2,0.0,-0.252294,0.695652,calm,calm,0.999167

In [14]:
encoded_emotions = emotion_encoder.fit_transform(data_matching_predictions["true_label"])
#encoded_concepts = concept_encoder.fit_transform(data_matching_predictions["concept_name"])

In [16]:
data_matching_predictions["true_label"] = encoded_emotions
#data_matching_predictions["concept_name"] = encoded_concepts

In [17]:
data_matching_predictions.head(13)

,path,concept_name,layer_name,positive_percentage,magnitude,cav_acc,true_label,predicted_label,predicted_probability
0,RAVDESS\original_data\Actor_23\03-01-02-02-02-...,long_constant_thick,module3.blocks.0.conv2,0.0,-0.479544,0.956522,1,calm,0.999167
1,RAVDESS\original_data\Actor_23\03-01-02-02-02-...,long_dropping_flat_thick,module3.blocks.0.conv2,0.0,-2.054141,0.869565,1,calm,0.999167
2,RAVDESS\original_data\Actor_23\03-01-02-02-02-...,long_dropping_steep_thick,module3.blocks.0.conv2,0.0,-0.572685,0.782609,1,calm,0.999167
3,RAVDESS\original_data\Actor_23\03-01-02-02-02-...,long_dropping_steep_thin,module3.blocks.0.conv2,0.0,-1.140559,0.913043,1,calm,0.999167
4,RAVDESS\original_data\Actor_23\03-01-02-02-02-...,long_rising_flat_thick,module3.blocks.0.conv2,0.0,-0.252294,0.695652,1,calm,0.999167
5,RAVDESS\original_data\Actor_23\03-01-02-02-02-...,long_rising_steep_thick,module3.blocks.0.conv2,0.0,-1.292134,0.869565,1,calm,0.999167
6,RAVDESS\original_data\Actor_23\03-01-02-02-02-...,long_rising_steep_thin,module3.blocks.0.conv2,0.0,-0.815764,0.826087,1,calm,0.999167
7,RAVDESS\original_data\Actor_23\03-01-02-02-02-...,short_constant_thick,module3.blocks.0.conv2,0.0,-0.217394,0.826087,1,calm,0.999167
8,RAVDESS\original_data\Actor_23\03-01-02-02-02-...,short_dropping_steep_thick,module3.blocks.0.conv2,0.0,-0.479893,0.739130,1,calm,0.999167
9,RAVDESS\original_data\Actor_23\03-01-02-02-02-...,short_dropping_steep_thin,module3.blocks.0.conv2,0.0,-0.958675,0.826087,1,calm,0.999167
10,RAVDESS\original_data\Actor_23\03-01-02-02-02-...,short_rising_steep_thick,module3.blocks.0.conv2,0.0,-0.814124,0.956522,1,calm,0.999167
11,RAVDESS\original_data\Actor_23\03-01-02-02-02-...,short_rising_steep_thin,module3.blocks.0.conv2,1.0,0.311537,0.826087,1,calm,0.999167
12,RAVDESS\original_data\Actor_02\03-01-07-01-02-...,long_constant_thick,module3.blocks.0.conv2,1.0,0.963829,0.956522,2,disgust,0.998985

In [89]:
vector_df = data_matching_predictions.pivot_table(
    index=["path", "true_label"],   # rows by recording
    columns="concept_name",      # each concept becomes its own column
    values="magnitude"          # the numeric values go in
).reset_index(drop = False)

In [92]:
vector_df

concept_name,path,true_label,long_constant_thick,long_dropping_flat_thick,long_dropping_steep_thick,long_dropping_steep_thin,long_rising_flat_thick,long_rising_steep_thick,long_rising_steep_thin,short_constant_thick,short_dropping_steep_thick,short_dropping_steep_thin,short_rising_steep_thick,short_rising_steep_thin
0,RAVDESS\original_data\Actor_01\03-01-01-01-01-...,5,-0.446786,-1.726427,-0.424797,-1.230913,-0.055599,-1.325301,-1.175653,-0.371397,-0.857731,-1.254580,-0.928992,0.077504
1,RAVDESS\original_data\Actor_01\03-01-01-01-02-...,5,-0.686852,-2.365001,-0.016568,-1.471219,0.366648,-1.863038,-1.228735,0.062346,-1.008595,-1.665167,-1.542318,0.371737
2,RAVDESS\original_data\Actor_01\03-01-01-01-02-...,5,0.058950,-1.018274,-0.156854,-0.511465,0.399225,-0.300722,-0.671590,-0.119173,-0.640000,-0.739923,-0.062474,0.228532
3,RAVDESS\original_data\Actor_01\03-01-02-01-01-...,1,-0.086732,-1.201567,0.135671,-0.674904,0.301109,-0.798481,0.353926,-0.327486,0.144517,-0.557534,-0.267235,0.392133
4,RAVDESS\original_data\Actor_01\03-01-02-01-01-...,1,-1.179929,-2.255814,-0.504839,-1.873528,-0.424320,-2.069821,-1.129922,-0.693433,-0.739755,-1.239145,-1.470185,0.006896
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1329,RAVDESS\original_data\Actor_24\03-01-08-01-02-...,7,2.127764,0.941703,1.533425,1.578726,1.506175,1.252627,1.318606,0.860395,0.440154,0.738477,1.597433,0.822107
1330,RAVDESS\original_data\Actor_24\03-01-08-01-02-...,7,2.494300,1.825770,2.021223,2.226799,1.920461,2.048605,2.136045,1.029077,1.033162,1.087814,2.624187,1.409729
1331,RAVDESS\original_data\Actor_24\03-01-08-02-01-...,7,2.354847,1.446679,1.402514,1.777966,1.513534,2.015508,1.992022,0.978621,0.892474,1.132352,2.334282,1.171509
1332,RAVDESS\original_data\Actor_24\03-01-08-02-02-...,7,2.596690,1.976899,1.404304,2.276531,1.693202,2.797426,2.210808,1.157644,1.113487,1.382582,3.190612,1.543425
1333,RAVDESS\original_data\Actor_24\03-01-08-02-02-...,7,2.781049,1.941040,1.439461,2.116549,1.847297,2.521635,2.188613,0.840019,0.956329,1.129114,2.774341,1.073377

In [93]:
# Features (X) and labels (y)
X = vector_df.drop(columns=["path", "true_label"], inplace=False).to_numpy()
y = vector_df["true_label"].to_numpy()

In [94]:
# ---- STEP 2: Clustering in Euclidean space ----
kmeans_euc = KMeans(n_clusters=len(set(y)), random_state=42, n_init="auto")
clusters_euc = kmeans_euc.fit_predict(X)

In [95]:
# ---- STEP 3: Clustering in Cosine space ----
# KMeans itself only works with Euclidean, but we can transform with cosine distances
# One option: Precompute cosine similarity, then embed with MDS
from sklearn.manifold import MDS

cosine_dist = cosine_distances(X)
mds = MDS(n_components=12, dissimilarity="precomputed", random_state=42)
X_cosine = mds.fit_transform(cosine_dist)

kmeans_cos = KMeans(n_clusters=len(set(y)), random_state=42, n_init="auto")
clusters_cos = kmeans_cos.fit_predict(X_cosine)

In [96]:
# ---- STEP 4: Evaluation (since you have ground truth labels) ----
print("Euclidean clustering ARI:", adjusted_rand_score(y, clusters_euc))
print("Cosine clustering ARI:", adjusted_rand_score(y, clusters_cos))
print("Euclidean Silhouette:", silhouette_score(X, clusters_euc))
print("Cosine Silhouette:", silhouette_score(X_cosine, clusters_cos))

Euclidean clustering ARI: 0.41341367810854185
Cosine clustering ARI: 0.4004969370107278
Euclidean Silhouette: 0.3110235018016217
Cosine Silhouette: 0.5461213313103594

In [99]:
def intra_inter_scores(X, y, metric="euclidean"):
    dist_matrix = pairwise_distances(X, metric=metric)
    labels = np.unique(y)

    intra_dists = []
    inter_dists = []

    for lbl in labels:
        idx = np.where(y == lbl)[0]
        if len(idx) > 1:
            # intra-label distances
            d = dist_matrix[np.ix_(idx, idx)]
            intra_dists.append(d[np.triu_indices_from(d, k=1)].mean())
    
    for i, lbl1 in enumerate(labels):
        for lbl2 in labels[i+1:]:
            idx1 = np.where(y == lbl1)[0]
            idx2 = np.where(y == lbl2)[0]
            d = dist_matrix[np.ix_(idx1, idx2)]
            inter_dists.append(d.mean())
    
    return {
        "intra_mean": np.mean(intra_dists),
        "inter_mean": np.mean(inter_dists),
        "separation": np.mean(inter_dists) / np.mean(intra_dists)
    }

print("Euclidean:", intra_inter_scores(X, y, metric="euclidean"))
print("Cosine:", intra_inter_scores(X, y, metric="cosine"))

Euclidean: {'intra_mean': 2.535917141622594, 'inter_mean': 5.334622626815398, 'separation': 2.10362654964431}
Cosine: {'intra_mean': 0.3351913099074862, 'inter_mean': 1.0833636849129804, 'separation': 3.2320756919742104}